services:
  - type: web
    name: daburguers
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn setup.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10